[package]
name = "kill-them-all"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
default = []
# Enables debug infos and rendering
dev = ["dep:bevy-inspector-egui", "bevy/bevy_dev_tools"]

[dependencies]
rand = "0.8"
bevy = { version = "0.15", default-features = false, features = [
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "multi_threaded",
    "default_font",
    "png"
] }
bevy_rapier2d = { git = "https://github.com/Vrixyz/bevy_rapier/", rev = "926a8bfc600e89d5f26a3a5ca27d4c7e4ab01c74"}
bevy-inspector-egui = { version = "0.28", default-features = false, features = [
    "bevy_render",
], optional = true }
bevy_ecs_tilemap = {git="https://github.com/bas-ie/bevy_ecs_tilemap", branch="0.15"}
